### PR TITLE
Add MacOS (darwin) support

### PR DESCRIPTION
**Pull request by dorinclisu**
- Re-used code from https://github.com/boppreh/keyboard (_darwinmouse.py) and adapted it to the event data structures used in this repo
- Tested on macos 11 (Big Sur).
- Solves #29 #30

### CODE REVIEW

**Comment by boppreh** [comment]
Looks great, thank you very much for your contribution!

**Comment by gutiere** [comment]
@boppreh, Can you publish this change to pypi? 🙏🏼

Would be greatly appreciated!

**Comment by JerryWeii-27** [comment]
Hi, I know this is old but when i do import mouse it still says that "OSError: Unsupported platform 'Darwin'". Is there any dependencies required?
I am using the latest version 0.7.1.

**Comment by Kazuma8** [comment]
> Hi, I know this is old but when i do import mouse it still says that "OSError: Unsupported platform 'Darwin'". Is there any dependencies required? I am using the latest version 0.7.1.
I have the same issue, I've tried running the .py files with sudo in terminal and I've also granted access to accessibility in Security and Privacy. I don't have this problem when using "keyboard". 

So, specifically what do I need to do in order to use "mouse" on a mac without the error mentioned above?

(I also noticed that mac support isn't mentioned in the __init__.py file for version 0.7.1)

**Comment by dorinclisu** [comment]
If you check the latest release (0.7.1) was released on Jan 1, 2020 and this PR was merged on Oct 28, 2020 so indeed darwin support is not there in the release.

Until the owner makes a new release, you can install from master like so:
`pip install https://github.com/boppreh/mouse/archive/master.zip`
The http url format is also supported in requirements.txt.

**Comment by nodox** [comment]
Can confirm this works for me

**Pull request merged**
